version: "3"
services:
  mysql:
    image: mysql:8.0
    container_name: project_mysql
    networks:
      default:
        ipv4_address: 192.168.2.3
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: project
      MYSQL_USER: project
      MYSQL_PASSWORD: project
    ports:
      - "3306:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: project_phpmyadmin
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    networks:
      default:
        ipv4_address: 192.168.2.4
    ports:
      - "81:80"

  web:
    build: ./.docker
    container_name: project_web
    networks:
      default:
        ipv4_address: 192.168.2.2
    volumes:
      - ./:/var/www/html/
      - ./.docker/virtualhost.conf:/etc/apache2/sites-available/000-default.conf
      - ./.docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./.docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
    ports:
      - "80:80"
    depends_on:
      - mysql

  mailhog:
    image: mailhog/mailhog
    container_name: project_mailhog
    ports:
      - "1025:1025" # smtp server
      - "8025:8025" # web ui
    networks:
      default:
        ipv4_address: 192.168.2.5

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.2.0/24
